version: "5.6"

services:
  zookeeper:
    restart: unless-stopped
    #    image: wurstmeister/zookeeper
    #    image: confluentinc/cp-zookeeper
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    expose:
      - "2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    restart: unless-stopped
    #    image: wurstmeister/kafka:0.8.1.1
    #    image: confluentinc/cp-kafka
    image: bitnami/kafka:3.2.3
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_OFFSET_RESET: earliest
      AUTO_OFFSET_RESET: earliest
    #      KAFKA_CREATE_TOPICS: topicName:1:10
    #      SASL_MECHANISM: AWS_MSK_IAM
    #      SECURITY_PROTOCOL: SASL_SSL
    #      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
    #      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
    #      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    depends_on:
      - zookeeper
#    volumes:
#      - ./:/etc/kafka


#https://www.baeldung.com/kafka-docker-connection
#
#
#services:
#  kafka:
#    image: 'confluentinc/cp-kafka'
#    ports:
#      - '29092:9092'
#    environment:
#      - KAFKA_ZOOKEEPER_CONNECT= zookeeperServ:2181
#      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_BROKER_ID=2
#      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
#      - KAFKA_CREATE_TOPICS= topicName:1:10
#    depends_on:
#      - zookeeperServ
#  zookeeperServ:
#    image: 'confluentinc/cp-zookeeper'
#    ports:
#      - "2181:2181"
#    environment:
#      - ZOOKEEPER_CLIENT_PORT=2181
#      - ZOOKEEPER_TICK_TIME=2000
#      - ZOOKEEPER_SYNC_LIMIT=2
#      - ALLOW_ANONYMOUS_LOGIN=yes
#services:
#  kafka:
#    image: 'bitnami/kafka:3.2.3'
#    restart: "no"
#    privileged: true
#    ports:
#      - 2181:2181
#      - 19092:19092
#    environment:
#      - KAFKA_ENABLE_KRAFT=yes
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:19092,CONTROLLER://:2181
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:19092
#      - KAFKA_BROKER_ID=1
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@127.0.0.1:2181
#      - ALLOW_PLAINTEXT_LISTENER=yes
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#      ZOOKEEPER_SYNC_LIMIT: 2
#  kafka:
#    image: confluentinc/cp-kafka
#    ports:
#      - 9094:9094
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL